name = "gluteboy"
account_id = "a69606fcc0fd66638f8562ef17f8e1eb"
workers_dev = true

[build.environment]
NODE_VERSION = "20.11.1"

[build]
command = "npm run build"
upload.dir = "./dist"
output.dir = "./dist"
pages_build_output_dir = "./dist"